package com.example.android.freetime.models;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Justin on 10/19/2017.
 */

public class Category {
    @DatabaseField(generatedId = true)
    private int CategoryID;

    @DatabaseField
    private String Description;

    public Category( ){

    }

    public Category(int categoryID, String description) {
        this.CategoryID = categoryID;
        this.Description = description;
    }

    public int getCategoryID() {
        return CategoryID;
    }

    //AutoGenerated ID could be dangerous to set
    public void setCategoryID(int categoryID) {
        CategoryID = categoryID;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String description) {
        Description = description;
    }
}
